
## Package documentation file.
##
## The file name is prefixed with `0_` , to ensure that it is processed first,
## so that @names/@rdnames are picked up here.
##
## It uses desc::desc_get() to get the description, instead of relying on
## autogenerated description. This is done in order to get markdown parsing and
## facilitate adding extra text to the package doc in addition to the text from
## the DESCRIPTION file.


#' @description
#' `r desc::desc_get("Description")`
#'
#' @import zmisc
#' @import zfit
#'
#' @docType package
#' @name zulutils
#' @md
#' @keywords internal
"_PACKAGE"


#' @title Deprecated functions in package \pkg{zulutils}.
#' @description The functions listed below are deprecated and will be defunct
#'   in the near future. When possible, alternative functions with similar
#'   functionality are also mentioned. Help pages for deprecated functions
#'   are available at \code{help("<function>-deprecated")}.
#' @name zulutils-deprecated
#' @rdname zulutils-deprecated
#' @keywords internal
NULL


#' @title Defunct functions in package \pkg{zulutils}.
#' @description The functions listed below are defunct. When possible,
#'   alternative functions with similar functionality are mentioned.
#' @name zulutils-defunct
#' @rdname zulutils-defunct
#' @keywords internal
NULL
